name: CI

on:
  push:
    branches: "**"
    pull_request:

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            swift: "6.0"
          - os: macos-14
            swift: "6.0"
          - os: macos-15
            swift: "6.0"
          - os: ubuntu-latest
            swift: "6.0"

    steps:
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift }}

      - run: swift --version
      - uses: actions/checkout@v3

      - name: test
        run: swift test

      - name: build for release
        run: swift build -c release

      - name: run example - nightshades
        run: swift run nightshades

      - name: run example - urls
        run: swift run urls
