name: CI

on:
  push:
    branches: "**"
    pull_request:

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-12
            swift: "5.9"
          - os: ubuntu-latest
            swift: "5.9"

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - run: swift --version
      - uses: actions/checkout@v3

      - name: test
        run: swift test

      - name: build for release
        run: swift build -c release

      - name: run example
        run: swift run
