name: CI

on:
  push:
    branches: "**"
    pull_request:

jobs:
  build:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: macos-13
            swift: "6.0"
          - os: ubuntu-latest
            swift: "6.0"

    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
        if: matrix.os == 'ubuntu-latest'
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
        if: matrix.os != 'ubuntu-latest'

      - run: swift --version
      - uses: actions/checkout@v3

      - name: test
        run: swift test

      - name: build for release
        run: swift build -c release

      - name: run example - nightshades
        run: swift run nightshades

      - name: run example - urls
        run: swift run urls
